### ISSUE TITLE
picasso---->IllegalArgumentException

### ISSUE THREAD

**Issue by leon2017** [Rance935/BeautyPaPa#2]
java.lang.IllegalArgumentException: Path must not be empty.
                                                                          at com.squareup.picasso.Picasso.load(Picasso.java:297)
                                                                          at com.rance.beautypapa.adapter.holder.VideoViewHolder.setData(VideoViewHolder.java:49)
                                                                          at com.rance.beautypapa.adapter.holder.VideoViewHolder.setData(VideoViewHolder.java:22)

加载更多的时候出现非法参数异常，估计没有设置默认加载图片，try一下？还是重新设计你的图片加载库？

**Comment by Rance935** [comment]
应该是默认图片的问题吧！谢谢提醒
